version: '3.8'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: blogapi-nginx
    volumes:
      - "./:/var/www/html"
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "9900:80"
      - "9901:443"
    restart: always
    depends_on:
      - backend
      - mysql
  backend:
    image: suleymanyilmaz/php8
    container_name: blogapi-backend
    restart: always
    volumes:
      - "./:/var/www/html"
      - "./.docker/deploy.sh/:/opt/deploy.sh"
  mysql:
    image: mysql:8.0
    container_name: blogapi-mysql
    restart: always
    volumes:
      - "./.docker/mysql/data:/var/lib/mysql"
      - "./.docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "9936:3306"
